### ISSUE TITLE
locate failing

### ISSUE THREAD

**Issue by BlackPR4** [johannesjo/linux-window-session-manager#12]
Command returns the error below when trying to save:

--------------------------------------

rayr@rayr-desktop:~/.lwsm$ lwsm save
locate *chrome-ojhjdjnggeknoafeebfnhpaldnmnlgdm*.desktop { [Error: Command failed: /bin/sh -c locate *chrome-ojhjdjnggeknoafeebfnhpaldnmnlgdm*.desktop
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c locate *chrome-ojhjdjnggeknoafeebfnhpaldnmnlgdm*.desktop' }
otherCmd: Generic Error { [Error: Command failed: /bin/sh -c locate *chrome-ojhjdjnggeknoafeebfnhpaldnmnlgdm*.desktop
]

I'm not sure I understand why locate is responding the way it is.  When running manually, it doesn't like anything after the dash.  But it doesn't mind the dash itself.   This would seem to be a problem with locate itself, but perhaps there's a workaround.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. Does executing `sudo updatedb` help?

**Comment by johannesjo** [comment]
I updated the lib not to use locate any more. So hopefully it should work now. If you encounter any problems please reopen.
