### ISSUE TITLE
No logging in case of failure

### ISSUE THREAD

**Issue by Gilthans** [johannesjo/linux-window-session-manager#14]
I've tried running the script (BTW, I recommend adding sudo apt-get install nodejs to the installation instructions :) ), but when I run 'lwsm save', move around a few windows, and 'lwsm restore', nothing happens and nothing is printed.
There weren't logs anywhere I could find, so I guess the request is more verbose failure so that I can know something went wrong (during save? during restore?), and have some tool to figure out the problem.
I'd be glad to post another issue with log information for my particular problem afterwards

**Comment by johannesjo** [comment]
Are you using Wayland by any chance. Pure Wayland applications are simply not recognized (and currently it seems there is no way around it :()

**Comment by Gilthans** [comment]
I'm using unity, which isn't over Wayland I believe? Either way it is probably a good idea to check and give an error, maybe?

**Comment by johannesjo** [comment]
Normally error logging should work. There are a lot of promises though. Might be that something gets swallowed there. I'll check tomorrow.

Could you maybe give me a little bit more of context? What applications do you have opened and what is saved inside ~/.lwsm?

**Comment by Gilthans** [comment]
I have many apps open, mostly chrome windows.
The .lstm folder does not exist/isn't created. I have tries running with
sudo, so this doesn't seem like a permissions issue.

**Comment by johannesjo** [comment]
Mhh that's interesting. Could you run `mkdir ~/.lwsm && mkdir ~/.lwsm/sessionData` and try again? If that doesn't work trying to save with just one or two apps might be helpful to be see if the issue is related to a particular app or occurs every time.

**Comment by Gilthans** [comment]
Creating the folders didn't seem to help, the folders are still empty after running `lwsm save` and `lwsm restore` with no message.
Closing apps would sort of defeat the purpose of trying to save the current setup which takes a while to bring up... But I'll try that later

**Comment by johannesjo** [comment]
I checked all promise occurrences and added catch handlers. Hopefully everything is covered now.

**Comment by Gilthans** [comment]
Was it uploaded to npm already or should I clone into the repo?

**Comment by johannesjo** [comment]
It was uploaded to npm already.

Daniel Rembiszewski <notifications@github.com> schrieb am Mi., 13. Dez.
2017 um 10:55 Uhr:

**Comment by Gilthans** [comment]
This didn't work, so I updated nodejs and that seemed to solve the problem.
Now I get this:

> /usr/local/lib/node_modules/linux-window-session-manager/cmd.js:3
> const base = require('./lib/index');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3
>

**Comment by johannesjo** [comment]
Äh what version of nodejs to you have installed now?

**Comment by Gilthans** [comment]
`node -v` returns `v0.10.25`

**Comment by Gilthans** [comment]
Yeah, so it seems there is something wrong with my app repo configurations which gave all this trouble. After manually installing node v8.9.3 everything seems to work perfectly.
Thanks very much!
