### ISSUE TITLE
Persist "Always On Top" & "Always on Visible Workspace"

### ISSUE THREAD

**Issue by wyqydsyq** [johannesjo/linux-window-session-manager#18]
## Your Environment

* Version used: 2.1.19
* Operating System and version: OpenSUSE Tumbleweed
* Desktop Environment: GNOME Shell 3.26.2
* Node version: v9.3.0

## Expected Behavior

Opening the context menu on a window and setting "Always On Top" or "Always on Visible Workspace" to true should result in these settings being saved and restored along with window positioning.

## Current Behavior
"Always On Top" and "Always on Visible Workspace" are not persisted.

## Steps to Reproduce (for bugs)

1. Open context menu for a window, set "Always On Top" or "Always on Visible Workspace"
2. Save session
3. Restore session
4. Notice the "Always On Top" or "Always on Visible Workspace" setting you just picked is now cleared

**Comment by johannesjo** [comment]
Hey there! Setting "Always On Top" works just fine on my machine (Ubuntu with Gnome). About "Always visible on workspace" I'm not sure to be honest. Executing
```
xprop -f _NET_WM_STATE 32a -set _NET_WM_STATE _NET_WM_STATE_STICKY
```
Manually seems to have no effect neither. Maybe it's an x11 issue?
