### ISSUE TITLE
 I get "undefined findDesktopFile cant find file; searched patterns" for like half the apps, why so much?

### ISSUE THREAD

**Issue by NinjaTurtle007** [johannesjo/linux-window-session-manager#22]
## Your Environment

* Version used: latest
* Operating System and version: ubuntu 18.04
* Desktop Environment: ubuntu gnome
* Node version:

## Expected Behavior
It should save all windows but it doesn't

## Current Behavior
It saved the session with bunch of errors and can't properly restore it later

I see this is discussed and is common bug, but it does that for half the applications I have. So instead of editing the paths for each one individually, maybe there is something more generally wrong that I can just fix instead of individually fixing each one of them?

I have quite popular setup, so I imagine that affects a lot of people. So, any ideas why it can't find the paths for soo much apps? 

## Steps to Reproduce (for bugs)
```
lwsm save test1
findDesktopFile cant find file; searched patterns [ '/home/user/.local/share/applications/Telegram.desktop',
  '/home/user/.local/share/applications/**/Telegram.desktop',
  '/home/user/.gnome/apps//Telegram.desktop',
  '/home/user/.gnome/apps//**/Telegram.desktop',
  '/usr/share/applications/Telegram.desktop',
  '/usr/share/applications/**/Telegram.desktop',
  '/usr/local/share/applications/Telegram.desktop',
  '/usr/local/share/applications/**/Telegram.desktop',
  '/usr/share/app-install/Telegram.desktop',
  '/usr/share/app-install/**/Telegram.desktop',
  '/home/user/.config/autostart//Telegram.desktop',
  '/home/user/.config/autostart//**/Telegram.desktop' ]
util: Generic Error findDesktopFile cant find file; searched patterns undefined
util: { '0': 'findDesktopFile cant find file; searched patterns' }
Input Handler Error:  No input for desktop file path for window "Telegram.TelegramDesktop". Please fix this manually in config file for this session in ~/.lwsm/{currentSessionName}.json

LWSM was unable to guess the location of your executable/desktop file.
 
There are two things, that you can do now: 
```

**Comment by johannesjo** [comment]
Hey there. Thanks for reporting. Where are those files which are not found, actually stored(e.g. for Telegram)? Best way to deal with this, is to add this location to the `~/.lwsm/config.json` under `DESKTOP_FILE_LOCATIONS`.

**Comment by NinjaTurtle007** [comment]
Ok after diving further all the problem apps seems to be installed via Snap and hence Appname.desktop is in the snap dir.

Another problem ones seem to be when you use multiple firefox profiles and start each of them with firefox1.desktop file in which you have a --no-remote command.

**Comment by johannesjo** [comment]
Let me know if this works for you!

**Comment by NinjaTurtle007** [comment]
Can you give an example of how to define them? Im very new to this.
Thank you!

**Comment by johannesjo** [comment]
Did you take a look at the config file? There are already some examples.

**Comment by johannesjo** [comment]
I expanded on the readme a little: https://github.com/johannesjo/linux-window-session-manager/blob/master/README.md

**Comment by NinjaTurtle007** [comment]
Well I finally edited the config file with the proper paths and saved it, but every time i run lwsm it restores it to the original config file.
I know because I leave the notepad open and it asks me to reaload the file because it has been changed on the disk and that happens as soon as i write "lwsm" in the terminal.

**Comment by johannesjo** [comment]
This should normally only happen when the config file is invalid json for some reason. Could you maybe post your config here?

**Comment by NinjaTurtle007** [comment]
Ok i have missed a coma but found all the issues. There are 2 because of the way snap stores files and names them.

1. It stores the .desktop files in "/var/lib/snapd/desktop/applications"
2. It also names them differently example: "telegram-desktop_telegramdesktop.desktop"


so if you want  to make lwsm snap compilant (and decrease the issues here :) )
Just make the default config file in the next version something like that.



`"WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    "gnome-terminal-server.Gnome-terminal": "gnome-terminal",
    "google-chrome.Google-chrome": "google-chrome.desktop",
    "Mail.Thunderbird": "thunderbird.desktop",
    "nautilus.Nautilus": "nautilus",
    "Navigator.Firefox": "firefox.desktop",
    "Navigator.Pale": "palemoon.desktop",
    "skype.Skype": "skypeforlinux.desktop",
    "sun-awt-X11-XFramePeer.jetbrains-idea": "jetbrains-idea.desktop",
    "VirtualBox.VirtualBox": "virtualbox.desktop",
    **"Telegram.TelegramDesktop": "telegram-desktop_telegramdesktop.desktop",
    "keepassxc.keepassxc": "keepassxc_keepassxc.desktop"**
  },`




`"DESKTOP_FILE_LOCATIONS": [
    "{home}/.local/share/applications",
    "{home}/.gnome/apps/",
    "/usr/share/applications",
    "/usr/local/share/applications",
    "/usr/share/app-install",
    "{home}/.config/autostart/",
    **"/var/lib/snapd/desktop/applications"**
  ],`


I've bolded the lines i've added in order to work correctly with snap apps

**Comment by johannesjo** [comment]
Thank you very much for digging into this! I'll include this in the next
release :)

NinjaTurtle007 <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
10:18:

**Comment by jjaone** [comment]
It doesn't work. Apps and windows do not get restored to correct workspaces, they all go to first worksapce always.
