### ISSUE TITLE
saveSession(): An error occurred Error: could not load data

### ISSUE THREAD

**Issue by NinjaTurtle007** [johannesjo/linux-window-session-manager#25]
> lwsm save test
saveSession(): An error occurred Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:11836) UnhandledPromiseRejectionWarning: Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:11836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SAVED SESSION: test

it used to work just fine shortly ago just saving the session without any errors, when i kept saving the same configuration (i was testing something related to other issue) it started throwing this error.

all latest versions

**Comment by johannesjo** [comment]
Hey, just looked into it. The error message is correct (it tries to open the session config file, which is not yet created), but misleading, as the program is operating normally and all should work as inteded. I'll replace it with a more helpful hint. Thanks for taking your time!
