### ISSUE TITLE
Enhancement: What if I want to get a list of my saved sessions? 

### ISSUE THREAD

**Issue by tecfu** [johannesjo/linux-window-session-manager#29]
Something like:

```bash
lwsm -l
```

**Comment by tecfu** [comment]
Usage: 

```
lwsm list
```

Since API already uses full words for other commands.

**Comment by johannesjo** [comment]
Thanks for the suggestion. Personally I have no need for such a feature, but I'm open for pull requests :) Meanwhile you can do this:
```
ls ~/.lwsm/sessionData
```
