### ISSUE TITLE
The top bar offset doesn't know when there is 2nd monitor with no top bar.

### ISSUE THREAD

**Issue by NinjaTurtle007** [johannesjo/linux-window-session-manager#33]
So it's smart that it takes into account the top bar and offsets the windows according to it BUT when you have 2nd monitor that has no top bar, it still does it.
So if you've placed your windows so they take the full 2nd monitor, save it, then restore it it positions them lower as if there is top bar when there is not.

So you have to manually readjust after each restore.

**Comment by mateusz-gozdek-sociomantic** [comment]
I just tested it and I think it's not the problems with the top bars. I use xfce4-panel and I added separated panel for each monitor to make top padding consistent and windows are still placed not quite correctly.

**Comment by johannesjo** [comment]
Maybe just a short note: The app just reads the data it gets from X11 and sends it back. I would assume that the inconsistency lies there, so apart from very complicated hacks around this, I don't really see a way to deal with this unfortunately.

I might be wrong of course :)
