### ISSUE TITLE
Please add '/snap/bin' to default search path

### ISSUE THREAD

**Issue by aojes** [johannesjo/linux-window-session-manager#35]
Using the latest lwsm package, I've rewritten the config to search /snap/bin and changes atom.Atom and mailspring.Mailspring classes' executables to 'atom' and 'mailspring' atop the entries for "WM_CLASS_AND_EXECUTABLE_FILE_MAP".

I'm using Ubuntu 18.10 minimal install. please let me know ifyou need more detail. thank you. it's a nice and more than welcome package for gnome.

**Comment by johannesjo** [comment]
Thanks for the suggestion! Should I add something for mailpring and atom as well?

**Comment by tidelake** [comment]
I'm not sure how the source comes together, but I had to add entries for them in the config file. Maybe all snap software comes that way. I'd like to go about it the right way and fork and PR, but I'm hungry.

**Comment by johannesjo** [comment]
Hehe. Alright then. Enjoy your meal!
