### ISSUE TITLE
Please add support for org.gnome.*desktop to default search matching

### ISSUE THREAD

**Issue by thefuzzyorange** [johannesjo/linux-window-session-manager#36]
Please can you add support for native gnome apps by prepending org.gnome to the .desktop file that is searched for.
Example : gedit.desktop is actually stored as org.gnome.gedit.desktop

## Your Environment
* Version used: 
* Operating System and version: Ubuntu 18.10
* Desktop Environment: Gnome 3.30
* Node version: 11.2.0

## Expected Behavior
I'd like the search pattern to also match by pre-pending org.gnome to the generated desktop filename

## Current Behavior
Does not find the .desktop file because the file is actually prepended with org.gnome.
To get a complete list run find / -name 'org.gnome*.desktop' 2>/dev/null

## Steps to Reproduce (for bugs)
1. Open some native gnome apps like gedit / calculator / logs
2. Run lwsm save test
3. Errors are logged that the .desktop file cannot be found.

**Comment by johannesjo** [comment]
Hey there! Thanks for opening up this issue. Not sure why I don't have the same problem on my machine (I have all the desktop files present without org.gnome being prefixed), but I provided an option to solve your problem.
You can know use `DESKTOP_FILE_PATTERNS` in your `config.json`.
Adding `/usr/share/applications/org.gnome.{fileName}` for example will search for desktop files which are prefixed with `org.gnome.` inside `/usr/share/applications`.

**Comment by thefuzzyorange** [comment]
Awesome! Thanks a mill!
