### ISSUE TITLE
Pass args to the application to open

### ISSUE THREAD

**Issue by brpaz** [johannesjo/linux-window-session-manager#37]
Hello.

Really great work on this tool. Its exactly what I was looking for, ;)

I would like to be able to start for example a specific website in Google Chrome or run some command when launching the terminal application that were saved in the session. Its possible to specify arguments, for example in the "executableFile" field of the session json file?

I dont except the application to be able to save stuff like Open tabs, when saving the session, but its a thing I can easily do manually if needed.

Thank you.

**Comment by johannesjo** [comment]
Hey there! Thanks for nice words :) 

Yes that should be possible. Instead of a desktop file you should be able to use any command. You just have to delete the `desktopFilePath` for the entry if set and use `executableFile` for the command you want to execute.

**Comment by brpaz** [comment]
Ah, I was missing the part of removing the `desktopFilePath`. I tested and it worked. ;)
