### ISSUE TITLE
Error when restoring; related to launching of Atom editor 

### ISSUE THREAD

**Issue by Samleo8** [johannesjo/linux-window-session-manager#38]
## Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Node version:

## Expected Behavior

Atom editor (installed via snap/Ubuntu store) opens successfully on `lwsm restore`

## Current Behavior

Throws an error: 
```
Generic Error in Main Handler Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:4107) UnhandledPromiseRejectionWarning: Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:4107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Interesting note:** When I first open the atom editor, _and then_ type the `lwsm restore` command, no errors are thrown and Atom is put in the place/desktop where I want it to go.

Thus I suspect that it has to do with lwsm not being able to find Atom in the EXECUTABLE_PATH in the config file.

I have already tried changed the config file to include paths to `atom.desktop`, but nothing worked. (also, `/snap/bin` is already there) 

**Current workaround:**

Open Atom first then run `lwsm restore` without trouble.

## Steps to Reproduce (for bugs)

1. `lwsm save` with Atom editor (and Terminal)
2. Close Atom editor
3. `lwsm restore` => _throws error_
4. Open Atom editor
5. `lwsm restore` => no error, places Atom in the correct workspace and position as expected

**Comment by johannesjo** [comment]
Did you try the things suggested in in the (troubleshooting section)[https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues]? You probably will have to add the path to atom yourself, as it is not matching the common pattern.

**Comment by Samleo8** [comment]
Yes I did :(

**Comment by Samleo8** [comment]
Apparently it's less to do with the path (which I already added), but the name of the desktop app: /var/lib/snapd/desktop/applications/**atom_atom.desktop** as opposed to /var/lib/snapd/desktop/applications/atom.desktop 

So to solve the issue I added the PATH and the atom_atom.desktop, which I think should be there as the default for the atom editor, unless somehow it's unique to only my computer.

**Comment by masip85** [comment]
Same here with Spotify:
Error: spawn spotify.desktop ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I tried adding spotify.desktop to WM_CLASS_EXCLUSIONS, but error persists.

**Comment by johannesjo** [comment]
@masip85 please follow the troubleshooting section in the readme. `spotify.desktop` is most likely not a valid name for `WM_CLASS_EXCLUSIONS`. I'm assuming its `spotify.Spotify`
