### ISSUE TITLE
lwsm works from command line but not the Gnome desktop extension

### ISSUE THREAD

**Issue by theWebalyst** [johannesjo/linux-window-session-manager#39]
## Your Environment

* Version used: 2.1.28
* Operating System and version: Ubuntu 18.10
* Desktop Environment: Gnome 3.30.1
* Node version: 8.11.3

## Expected Behavior
I have the Gnome lwsm desktop extension installed and want to be able to save and load using that.

## Current Behavior
I can save and restore using the command line, and saved sessions are listed in the desktop extension, but when I attempt to save or restore using the desktop extension I see a status notification "lwsm: save test" for a couple of seconds, and then it changes to "lwsm: save test UNKNOWN ERROR".

I get the same result if I try to restore one of the sessions saved using the command line. But if I restore from the command line, it works fine.

I tried changing the path in the extension config but can confirm that is correct (because if I invalidate it I get an error about it not finding the executable).

The extension is accessible in gnome 'tweak UI', and I can use that to change the path to lwsm, and to enable and disable the extension.

## Steps to Reproduce (for bugs)
Click on the extension icon, type a description and click the save icon.

NOTE: I have nvm installed and had problems locating the executable because I'm using node 8.12 by default, but somehow have lwsm installed only for 8.11.3. So to use lwsm in the terminal I have to `nvm use 8.11.3` first. This doesn't appear to be related, but I mention it in case. I'm also wondering how to fix this! For now I'll just use an alias for lwsm.

## Supplementary Question:
Is there a simple way to have the terminal windows restored to their current directory?

**Comment by johannesjo** [comment]
Hey there. What you could try is to fiddle with the extension setting "Path to lwsm" you can find it under the "extension panel" in the "tweaks" application. On my system – also using nvm, but also yarn – that's `/home/myuser/.config/yarn/global/node_modules/.bin/lwsm`.

Let me know if this works out for you.

**Comment by theWebalyst** [comment]
Thanks, but I already confirmed that the party is OK:

> I tried changing the path in the extension config but can confirm that is correct (because if I invalidate it I get an error about it not finding the executable).

**Comment by johannesjo** [comment]
Sorry. I missed that part. The question is what the correct path means. You need the path to the one used by Ubuntu in a book login shell, which might be a different one. There are several possibilities. It's hard to guess but you could try the node version shipping with Ubuntu and install lwsm globally for that. Adding the nvm node version to the .profile might be another option.

**Comment by theWebalyst** [comment]
No worries, I could have been clearer :smile:

I don't understand why you think the path is the issue. If I set an invalid path I get a different result (a few seconds delay and then a different error) which suggests `lwsm` is running. 

Is that what you'd expect if I wasn't using the 'one used by Ubuntu in a book login shell'? (I assume you mean 'bash' not 'book' there). 

And do you really mean 'login shell' or just 'bash terminal'?

**Comment by johannesjo** [comment]
Another alternative would be debugging the gnome shell extension directly, by using `lg`: https://stackoverflow.com/questions/8425616/how-to-test-debug-gnome-shell-extensions-is-there-any-tool-for-that

I'm assuming that, because the extension might not use the node version defined by nvm, as this usually set by same configuration in the .bashrc etc. Could be a different issue of course.

**Comment by theWebalyst** [comment]
> It's not really a login shell, but in the context of the extension the .bashrc is most likely not loaded.

Seems a reasonable bet. In the meant time I have traced and fixed an issue I had with nvm/node but that hasn't solved this. So I have used `lg` as suggested, but it gives not more info. I can 'Show Errors' for the `lwsm` extension, but it says it hasn't generated any errors yet, and it stays like that even when I get the 'UNKNOWN ERROR' notification trying to save using the extension. So maybe the extension isn't generating error output, but just failing and returning an error code. 

I tried removing it with `npm` and installing with `yarn global add linux-window-package-manager` and then updating the path for the extension but the symptoms haven't changed.

I tried using both the path which is a symlink, and the path that the symlink points to (as you are: /home/myuser/.config/yarn/global/node_modules/.bin/lwsm). No improvement!

It is definitely finding and running the executable: if I add a spurious character to the path I get an immediate `Error: no lwsm executable` and telling me to set the path correctly.

So I suspect `lwsm` runs, does some work (for about seven seconds), and then tries to do something which causes it to exit prematurely, but without an error message. Any ideas what it might be failing on - permissions maybe?

**Comment by johannesjo** [comment]
Thanks for the effort your putting into this.

I'm assuming that restoring or saving the very same configuration of open applications runs fine from the command line? I'm running out of ideas then. :( 

One more thing you could do is to add some more logging to the extension itself. I don't have my laptop with me atm the moment so I can't give you detailed instructions. The file of the extension is this one: https://github.com/johannesjo/gnome-shell-extension-window-session-manager/blob/master/extension.js

With global.log you can print stuff to the weird lg console. Would be interesting to know what error the lwsm command is throwing...

**Comment by theWebalyst** [comment]
Just took a quick look at the code and the error message (UNKNOWN ERROR) suggests `lwsm` executes ok (although it doesn't create a new session so I may be wrong here) because:

https://github.com/johannesjo/gnome-shell-extension-window-session-manager/blob/master/extension.js#L279

No time to debug more for now, but I'll probably poke more at some point.

**Comment by johannesjo** [comment]
There is a watcher for the exit code of lwsm. If the error code is anything else than `0` the message appears (the wording could probably be better). So it means that lwsm is throwing some sort of error. I don't know what the proper way is to get the console output. The only documentation available is for the C (Rust??) version of the lib (https://developer.gnome.org/pygobject/stable/glib-functions.html#function-glib--child-watch-add). It's really not much fun programming gnome shell extensions...

**Comment by theWebalyst** [comment]
Small update. Info from `extension.js / _execLwsm` 

executable looks file
success is 'true' (`lwsm` has spawned ok)
status is 32512 (web search not too helpful, but others have reported this error when spawning. It maps to 7F0 / 127 which might well be command not found, although it seems odd this would take 7 seconds)

So I tried changing `executable` to '/bin/ls' and, this is strange. I still get an error, but a different status (512 instead of 32512). This suggests the 32512 is indeed that it's not finding the `lwsm` exectutable.

I've messed around a bit further, but not really getting anywhere!

**Comment by johannesjo** [comment]
That's all rather confusing to me to be honest. Maybe it's related to the gnome version installed? Maybe they changed or even broke something. Can't really tell you atm which version I got, but I'm pretty sure that it is older than 3.30.1.

**Comment by johannesjo** [comment]
I am closing this. Please let me know if the issue persists with the newest version.
