### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by nkovshov** [johannesjo/linux-window-session-manager#4]
What about command-line completion?
I think about action and session name completion.
[Omelette](https://www.npmjs.com/package/omelette) may be a good lib to implement this.

**Comment by johannesjo** [comment]
Excellent suggestion. I'd like this to happen. Would you like to implement it yourself? Looks like it should be pretty straight forward. Have a look here: https://github.com/johannesjo/linux-window-session-manager/blob/master/cmd.js

Starting from line 44 is the current code.
