### ISSUE TITLE
lwsm saves applications to session even when it can't find their path

### ISSUE THREAD

**Issue by wizonesolutions** [johannesjo/linux-window-session-manager#44]
## Your Environment

* Version used: 2.1.31
* Operating System and version: Ubuntu 18.04
* Desktop Environment: GNOME 3
* Node version: v8.10.0

When running `lwsm save`, it fails to save some apps that aren't mapped yet. I'm was OK with that because I was testing, so I didn't fix them. I figured it would ignore them.

## Expected Behavior

`lwsm save` should not include apps that it won't be able to re-open in the session.

## Current Behavior

`lwsm save` includes all detected apps, even those for which it encountered an error during save, in the session file, then tries (and fails) to restore them.

Workaround is to open apps manually and run `lwsm restore` until it works.

## Steps to Reproduce (for bugs)

1. Install an unsupported app like Toggl Desktop https://github.com/toggl/toggldesktop/releases
2. `lwsm save`
3. Restart (or just close some apps)
4. `lwsm restore`

You wind up with something like:

```
⋊> ~ lwsm restore                                                                                                                                                                                          10:09:59
Status: "crx_pofoocnjclhmhkhkgibipddgekdlnfmj.Brave-browser" is running: true 1 0
Status: "crx_ddiddklncfgbfaaahngklemobghhjkim.Brave-browser" is running: true 1 0
Status: "brave-browser.Brave-browser" is running: true 1 0
Status: "Telegram.TelegramDesktop" is running: true 1 0
Status: "caprine.Caprine" is running: true 1 0
Status: "discord.discord" is running: true 1 0
Status: "TogglDesktop.Toggl Desktop" is running: false 1 0
Starting: TogglDesktop.desktop
Status: "terminator.Terminator" is running: true 1 0
Status: "slack.Slack" is running: true 1 0
Status: "Mail.Thunderbird" is running: true 2 0
Status: "Mail.Thunderbird" is running: true 2 0
Status: "sun-awt-X11-XFramePeer.jetbrains-phpstorm" is running: true 1 0
Status: "todoist.Todoist" is running: true 1 0
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn TogglDesktop.desktop ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

btw, this actually works better than I expected. I didn't realize it'd set window positions (or I just forgot), and the running app detection is great! I was worried about my startup apps getting in the way. Useful tool!

**Comment by johannesjo** [comment]
Thanks for opening up this issue. Your probably right about this, even though showing the error might lead more people to post broken configs here.

To be honest this is not on the top of my todo list as I'm quite busy with [another project](https://github.com/johannesjo/super-productivity) and because I will be on vacation for a while. Pull Requests are always welcome though :)
