### ISSUE TITLE
Most of applications don't recover

### ISSUE THREAD

**Issue by ZerdoX-x** [johannesjo/linux-window-session-manager#45]
- Ubuntu 19.04
- Node v10.16.3

Opera:
```
zerdox@zerdox-A320M-H:~$ lwsm restore
Status: "Opera developer.Opera developer" is running: false 1 0
Starting: Opera developer.desktop
Status: "google-chrome-unstable.Google-chrome-unstable" is running: false 1 0
Starting: google-chrome-unstable.desktop
Status: "gnome-terminal-server.Gnome-terminal" is running: true 1 0
Wait for all applications to start
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn Opera ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Visual Studio: 
```
zerdox@zerdox-A320M-H:~$ lwsm restore
Status: "gnome-terminal-server.Gnome-terminal" is running: true 1 0
Status: "Opera developer.Opera developer" is running: true 1 0
Status: "code - insiders.Code - Insiders" is running: false 1 0
Starting: code - insiders.desktop
Wait for all applications to start
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn code ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I guess 19.04 is not supported? Any alternatives?

**Comment by johannesjo** [comment]
Just a guess: are you using wayland?

If so, please have a look at the troubleshooting section.

**Comment by ZerdoX-x** [comment]
> are you using wayland?

I'm not sure because I'm new to Linux, but I guess I'm using Xorg. I uploaded photo to be clear.
![IMG_20190925_183902](https://user-images.githubusercontent.com/49815452/65606517-791c6980-dfc4-11e9-912e-25824cbade53.jpg)
I have tried to login to Ubuntu on Wayland and surprisingly, it works better for me, all apps restore but they all are in one worspace, even I saved 9 windows on 4 workspaces. Am I need to move to Wayland, or still use Xorg?

**Comment by johannesjo** [comment]
It works better with Wayland? Well it certainly should be the other way round :)

Why would you need to run it as root, i wonder?

**Comment by ZerdoX-x** [comment]
On Xorg - errors, on Wayland - lwsm can't remember in which workspace which window.

I tried to run it as root because some apps can't get profile settings, I thought it will help.. 

So now I have two problems on Wayland: 
- lwsm doesn't recover workspaces (main problem)
- some apps can't get profile data, I guess when they are ran with lwsm, they don't have much permissions.

And one big problem on Xorg I described above - it just doesn't work.

**Comment by johannesjo** [comment]
You can probably add opera to your config file like described in the troubleshooting section. Workspaces won't probably work on Wayland, because it is very niggardly regarding the information it gives away.

**Comment by ZerdoX-x** [comment]
I just have reinstalled this, now it works in Xorg. But GitKraken, Tusk, Avacode for example, still can't get profile (feels like I'm in portable version of app). 

> You can probably add the missing applications to your config file like described in the troubleshooting section in the readme.
And could you please write about this in more detalis. I can't understand troubleshooting section clearly. Where I need to add this if I haven't config file? How can I find name of .desktop file of running application? Thank you for your help.. I'm not very good at english and also I'm new to linux, so it's very hard for me, hope you'll understand. 

Attached video how lwsm can't see dev version of chrome and can't login in Gitkraken
https://youtu.be/YW3JIQC8oeA

**Comment by ZerdoX-x** [comment]
Oh.. I'm so stupid.. In last vid I was using another script. I'm so sorry

**Comment by ZerdoX-x** [comment]
Please watch this, I was trying to fix problem same as in troubleshooting section, what was I doing wrong?

https://youtu.be/0QIAIjDgkio

**Comment by ZerdoX-x** [comment]
I have edited string in /usr/share/applications/opera-developer.desktop
"name=Opera developer" to "name=opera-developer". Now it works great with opera, but how can I add other applications without editing their .desktop file?

**Comment by johannesjo** [comment]
You don't need to edit the desktop files. You need to edit your config, as stated in the troubleshooting section of the readme and the output you get when executing lwsm from the command line :)

To quote the readme:
> 1. You can locate the executable or desktop file manually for the application  which isn't started (e.g. via the locate command), and add it to `~/.lwsm/{currentSessionName}.json`. 
If you want to persist that mapping you might also want to open `~/.lwsm/config.json`  and edit the `WM_CLASS_AND_EXECUTABLE_FILE_MAP` property. You can find out which property name to use by executing `xprop` and clicking on an open window of the application. Look for `WM_CLASS(STRING)` (Or just execute `xprop | grep "WM_CLASS(STRING)"`). For finding the desktop file the `locate` command is usful (e.g.: `locate google-chrome.desktop`).

```
 // ~/.lwsm/config.json
 "WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    "{result of xprop}": "opera-developer.desktop",
  },

**Comment by ZerdoX-x** [comment]
But it doesn't work, have you seen the video?

> https://youtu.be/0QIAIjDgkio

**Comment by ZerdoX-x** [comment]
I have just found that config doesn't save after I reload pc, what's wrong?

**Comment by johannesjo** [comment]
What doesn't save?

**Comment by ZerdoX-x** [comment]
Sorry for bad english. I mean config isn't saved (passive voice, english grammar)

**Comment by johannesjo** [comment]
You mean the config. json?

**Comment by ZerdoX-x** [comment]
yes, when I edit it, lwsm can't see changes (as in video), and when i reload my pc, all changes disappears

**Comment by johannesjo** [comment]
When do the changes disappear? When  you reload your pc or after executing the application?

**Comment by ZerdoX-x** [comment]
after I reload my pc

**Comment by ZerdoX-x** [comment]
![image](https://user-images.githubusercontent.com/49815452/65813671-e7923f00-e1f1-11e9-9d92-9397849d7c3b.png)
also I cant ignore apps (file is saved)

**Comment by ZerdoX-x** [comment]
I have found the problem and I have fixed this, I am going to describe problem and how to fix it soon, hope you will add this to readme.

**Comment by ZerdoX-x** [comment]
### How to recognise problem:

- Your applications can't restore (e.g. `Error: spawn Opera ENOENT`)
- When you save session there are a lot of lines of text (screenshot below)

![image](https://user-images.githubusercontent.com/49815452/65815194-97bd7300-e205-11e9-82b0-2b8cc84fa629.png)

**DO NOT TRUST LAST LINE**
`SAVED SESSION: test` — that's not true. 

### How to fix problem: 

1. Find name of your application in this log (e.g. "Opera developer.Opera developer")
![image](https://user-images.githubusercontent.com/49815452/65815249-ab1d0e00-e206-11e9-8e49-77c053036809.png)

2. Find .desktop file of your application

    - You can do it like this from cli: `locate *<keyword of application's name>*.desktop`
      ```
      zerdox@zerdox-A320M-H:~$ locate *opera*.desktop
      /usr/share/applications/opera-developer.desktop
      ```
    - Or you can locate into your applications directory and find it there:
    ![image](https://user-images.githubusercontent.com/49815452/65815405-71e59d80-e208-11e9-8d39-24e8dccae0dc.png)

3. Write name of your application from first paragraph and your .desktop file's name into ~/.lwsm/config.json like this
Find "WM_CLASS_AND_EXECUTABLE_FILE_MAP" object and put in it a new value
```
"WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    ...
    ...
    "Opera developer.Opera developer": "opera-developer.desktop",
},
```

4. Save session again (make sure you have closed every window except problematic application)
```
zerdox@zerdox-A320M-H:~$ lwsm save test
SAVED SESSION: test
```

Now, when you got only one line `SAVED SESSION: test` you can restore session. Now you have added this application to config.

_If you will try to save and restore session with two or more problematic apps, your config.json may resets to it's default, you need to add applications one by one._

And finally, when you have added all apps to config, you can use lwsm correctly.

**Comment by ZerdoX-x** [comment]
Hope this will help someone. Please add more info to your troubleshooting section and use section of readme. Thank you very much <3

**Comment by ZerdoX-x** [comment]
And using xprop in this case is bad practise: 
```
zerdox@zerdox-A320M-H:~$ xprop | grep "WM_CLASS(STRING)"
WM_CLASS(STRING) = "Opera developer", "Opera developer"
```
But I would need "Opera developer.Opera developer"

I tried just to copy result of xprop and just put dot between to names, but this is not working with other apps, it's more reliable to copy name from lwsm log after saving session

**Comment by johannesjo** [comment]
Thanks for sharing your solution! Glad that it works now for you. I'll extend the troubleshooting section with your guide.
