### ISSUE TITLE
lwsm doesn't work if it used with shortcut

### ISSUE THREAD

**Issue by ZerdoX-x** [johannesjo/linux-window-session-manager#46]
## Your Environment
* Operating System and version: Ubuntu 19.04
* Desktop Environment: Xorg. wm - gnome

## Expected Behavior
restore all windows and workspaces from default session

## Current Behavior
lwsm doesn't work, when I press ctrl + shift + r command "lwsm restore" doesn't executed, nothing happens

![image](https://user-images.githubusercontent.com/49815452/66176028-8e089500-e675-11e9-8e64-39e16ee15634.png)

**Comment by johannesjo** [comment]
That might be because your linked user binaries might not be available in this context. What you can do is, execute:
```
which lwsm
``` 
from the terminal and use this path instead of just `lwsm`.

**Comment by ZerdoX-x** [comment]
nope, still doesn't work, nothing changed
![image](https://user-images.githubusercontent.com/49815452/66207532-714b7c00-e6cc-11e9-9a2c-54971da7b410.png)

**Comment by johannesjo** [comment]
Hm. Worked for me. What's the output of `/home/zerdox/.nvm/versions/node/v10.16.3/bin/lwsm restore`?

**Comment by ZerdoX-x** [comment]
same as `lwm restore`, I have tried already, before creating shortcut

**Comment by johannesjo** [comment]
You can also try one of the following:

https://ubuntuforums.org/showthread.php?t=1540961
https://askubuntu.com/questions/604858/run-shell-script-on-keyboard-shortcut

**Comment by ZerdoX-x** [comment]
tried to chmod x+u and add `sh` or `bin/sh` before command tp execute. nothing.

**Comment by johannesjo** [comment]
Did you try this:
```
gnome-terminal -e "/home/zerdox/.nvm/versions/node/v10.16.3/bin/lwsm restore"
```
?

I assume that this is related to using nvm and that the command is not available for some reason in the context where the shortcut is executed. Also maybe you want to try updating to the latest version of lwsm even though it's probably not related.

**Comment by ZerdoX-x** [comment]
appears pop-up for a half of a second, that terminal window is waiting. windows do not restore

**Comment by johannesjo** [comment]
If you execute
```
gnome-terminal -e "/home/zerdox/.nvm/versions/node/v10.16.3/bin/lwsm restore && sleep 30000"
```
You should hopefully be able to see the error message.

**Comment by ZerdoX-x** [comment]
nope. same. can't see error

**Comment by johannesjo** [comment]
One more thing you can try:
```
node /home/zerdox/.nvm/versions/node/v10.16.3/bin/lwsm restore 
```

**Comment by grssnbchr** [comment]
I have exactly the same issue, Gnome 3.36... has anyone found a solution?
