### ISSUE TITLE
Can not install from current user

### ISSUE THREAD

**Issue by jerome-diver** [johannesjo/linux-window-session-manager#51]
## Your Environment

* Version used: 
* Operating System and version: Archlinux
* Desktop Environment: Spectrwm or i3 or deepin
* Node version: 10.17.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): any (Java or Qt5 or what ever, i hope a Windows Session Manager to be able to manage windows session

## Expected Behavior

Install it

## Current Behavior

npm install from current user failed with error access to file /usr/bin/node_modules

**Comment by johannesjo** [comment]
This is a problem of your node installation:
https://www.google.com/search?q=install+node+as+user+ubuntu&oq=install+node+as+user+ubuntu&aqs=chrome..69i57.9161j0j7&sourceid=chrome&ie=UTF-8

**Comment by jerome-diver** [comment]
@johannesjo ok. thank you.
Mine is just installed from archlinux official repository, but it may have an other one problem also around (i did something i remember for a React dev test).

**Comment by johannesjo** [comment]
It's a long standing issue with the system installation of node on linux desktops. I might want to add a hint on the readme page :)
