### ISSUE TITLE
Save and Restore both crash when I have a Google Hangouts window open

### ISSUE THREAD

**Issue by soapergem** [johannesjo/linux-window-session-manager#52]
## My Environment

* Version used: Linux Window Session Manager 3.0.7
* Operating System and version: Ubuntu 18.04 bionic (x86_64 Linux 5.0.0-37-generic)
* Desktop Environment: GNOME 3.28.2
* Node version: 13.0.1
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): 
  * Slack
  * Tilix
  * SmartGit
  * VSCode
  * GEdit
  * Google Chrome
  * Google Hangouts (Chrome extension; creates its own window)

## Expected Behavior

Typing `lwsm save` should work.

## Current Behavior

As long as the Hangouts extension window is open, `lwsm save` will actually never terminate - it will hang indefinitely and I will have to Ctrl - C to kill it. But not before first printing out the following error messages:

```
findDesktopFile cant find file; searched patterns []
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
Generic Error in Meta Wrapper findDesktopFile cant find file; searched patterns undefined
(node:11486) UnhandledPromiseRejectionWarning: findDesktopFile cant find file; searched patterns
(node:11486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce (for bugs)

1. Install LWSM
2. Install Google Chrome
3. Install the [Google Hangouts extension](https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd?hl=en) for Chrome
4. Click the Hangouts button in Chrome to pop open a new window
5. Type `lvsm save`

**Comment by soapergem** [comment]
Similarly, it will crash on `lwsm restore` if I have that Hangouts window open. (I saved a profile with it closed first.)

**Comment by johannesjo** [comment]
Thank you very much for reporting. Good catch! It's probably not possible to launch the window from lwsm, but it should at least ignore it.

**Comment by johannesjo** [comment]
Could you maybe do me a favor? If you open up the console and type `xprop` and then click on the extension window, what's the console output?

**Comment by soapergem** [comment]
I'm not too familiar with the `xprop` utility having never used it before. When I run it from my terminal it just hangs - until I Ctrl - C out of it.

**Comment by soapergem** [comment]
Oh! I just noticed you said "and then click"... I had no idea a terminal utility could capture mouse click events like that. Here's the output:

```
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 30, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_USER_TIME(CARDINAL) = 686745
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 960, 57
		program specified minimum size: 1 by 1
WM_NAME(UTF8_STRING) = "Google Hangouts - soapergem@gmail.com"
_NET_WM_NAME(UTF8_STRING) = "Google Hangouts - soapergem@gmail.com"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (16 x 16):
	     ░░▒▒░░     
	    ░▒▒▒▒▒▒▒    
	   ▒▒▒▒▒▒▒▒▒▒   
	  ▒▒▒▒▒▒▒▒▒▒▒▒  
	 ░▒▒▒▒▒▒▒▒▒▒▒▒░ 
	 ░▒▒░  ░░  ░▒▒░ 
	 ▒▒▒░  ░░  ░▒▒▒ 
	 ▒▒▒░  ░░  ░▒▒▒ 
	 ░▒▒▒▒ ░▒▒ ░▒▒░ 
	 ░▒▒▒▒░▒▒▒░▒▒▒░ 
	  ▒▒▒▒▒▒▒▒▒▒▒▒  
	   ▒▒▒▒▒▒▒▒▒▒░  
	    ░▒▒▒▒▒▒▒░   
	      ░░▒▒▒░    
	        ▒▒░     
	        ░       

	Icon (16 x 16):
	     ░░▒▒░░     
	    ░▒▒▒▒▒▒▒    
	   ▒▒▒▒▒▒▒▒▒▒   
	  ▒▒▒▒▒▒▒▒▒▒▒▒  
	 ░▒▒▒▒▒▒▒▒▒▒▒▒░ 
	 ░▒▒░  ░░  ░▒▒░ 
	 ▒▒▒░  ░░  ░▒▒▒ 
	 ▒▒▒░  ░░  ░▒▒▒ 
	 ░▒▒▒▒ ░▒▒ ░▒▒░ 
	 ░▒▒▒▒░▒▒▒░▒▒▒░ 
	  ▒▒▒▒▒▒▒▒▒▒▒▒  
	   ▒▒▒▒▒▒▒▒▒▒░  
	    ░▒▒▒▒▒▒▒░   
	      ░░▒▒▒░    
	        ▒▒░     
	        ░       


_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 44040251, 44040252
WM_WINDOW_ROLE(STRING) = "pop-up"
WM_CLASS(STRING) = "crx_nckgahadagoaajjgafhacjanaoiihapd", "Google-chrome"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 2454
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "gmyers-librem-15"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

**Comment by johannesjo** [comment]
Thank you very much! What you can do for now is to add the app the exclusion list in your config file to `WM_CLASS_EXCLUSIONS: [..., 'crx_nckgahadagoaajjgafhacjanaoiihapd.Google-chrome']`

**Comment by soapergem** [comment]
Perfect, now at least it's not crashing. It appears as if it ignores the window when I save; it closes the Hangouts window when I restore. Do you think with any future release, it would be possible to try and better support extension windows like this? Either don't close the window restore, or even try and resize it (when necessary) if present?

**Comment by johannesjo** [comment]
It's really difficult to find a generic solution here and easy to mess things up. Every application with different windows has different methods and perquisites to open them. Let's say I implement some special handling for different chrome windows, but this might conflict with chrome already handling that itself. 

If your extension would be a PWA instead, this should work.

Don't know... I'll experiment with it a little.

**Comment by johannesjo** [comment]
I worked a little bit on the problem. For now I am excluding pop up windows completely. But if you're interested in helping me, I see another option:
1. We still parse the information from the popup windows.
2. Lwsm doesn't try to open an application, because most likely these windows will be opened up by their parent application in a specific manner.
3. But if the window is there, lwsm will restore it to it's saved position.

If 2 doesn't work for your case, if the popup won't open up on chrome startup you might also adding a custom mapping of a specific command to the apps wmClassName (`crx_nckgahadagoaajjgafhacjanaoiihapd.Google-chrome'). In this case we would have to remove the pop-up exclusion mechanism I added.

Would you like to give it a shot? :) The code is a little bit messy to be honest, so it might not be that much fun to work with it, but I happily help you with any question, you might have.
