### ISSUE TITLE
Not positioning new official microsoft teams app

### ISSUE THREAD

**Issue by masip85** [johannesjo/linux-window-session-manager#54]
I've added to config.json line for using microsoft teams official app.
This is the class:
WM_CLASS(STRING) = "microsoft teams - preview", "Microsoft Teams - Preview"

I've added to lwsm config:
"microsoft teams - preview.Microsoft Teams - Preview":"/usr/bin/teams"

EXPECTED:
Opening and positioning Microsoft teams desktop.
BEHAVIOUR: 
It only opens,doesn't position it. But, if it is previously opened to the lwsm restoring, it is positioned.

**Comment by johannesjo** [comment]
That's interesting. Did you encounter this issue only with the teams app or also with something else?

**Comment by masip85** [comment]
This is the first time

**Comment by johannesjo** [comment]
Thank you! I look into it.

**Comment by johannesjo** [comment]
Adding
```
        "microsoft teams - preview.Microsoft Teams - Preview": "teams.desktop"
```
to your config.json under `WM_CLASS_AND_EXECUTABLE_FILE_MAP` should fix the issue.
