### ISSUE TITLE
More specific save/restore of application states

### ISSUE THREAD

**Issue by jbueghly** [johannesjo/linux-window-session-manager#55]
Hello, 

I'm just starting to use this, so I don't know the exact expected behavior. Right now, when I save a session, I am able to restore the windows and applications, but the applications all open to their initial states. For example, terminals open to the default home area, and PDFs open to the general PDF application, but not specific files. Is it possible, for example, to save a session with a terminal open on a file with a text editor, or the PDF application open on a specific file?

**Comment by johannesjo** [comment]
@jbueghly you can basically run every custom command you like by directly editing the saved session file under `~/.lwsm/sessionData/...`. 
So you could add `gedit myfile` or something similar there.

The tool can't persist these things automatically however and it probably never will be able to as for some applications this might not be desirable for a multitude of reasons, while it might be impossible to guess for others.

**Comment by jbueghly** [comment]
Thanks for getting back to me. Could you give a bit of detail on how to insert an example command into the JSON file? I see the various windows in the list with their parameters. I'm not sure what parameter should be entered to run a command within the window.

**Comment by johannesjo** [comment]
You can edit `executableFile` to contain any command you'd like. How this command looks like depends on the application you are using. You could try using the `man` command, e.g.:
```
man gedit
```
Otherwise google is your friend.
