### ISSUE TITLE
Windows are not restored to their initial desktop in Gnome 3

### ISSUE THREAD

**Issue by Fr33maan** [johannesjo/linux-window-session-manager#56]
Great job, everything is almost working perfectly !

## Your Environment

* Version used: 3.0.8
* Operating System and version:  Ubuntu 18.04
* Desktop Environment: Gnome 3
* Node version: 12.10
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): VSCode

## Expected Behavior
Ideally, each window would open at its exact desktop

## Current Behavior
All VSCode windows are open on the same desktop instead of going back to their respective desktops.

## Steps to Reproduce (for bugs)
1. My desktop number is fixed, I have 6 desktop. Eventually switch from flexible number of desktops to a fixed number.
2. Open 3 VSCode windows on 3 different desktop, save, close then restore.

**Comment by johannesjo** [comment]
Hey! Thanks for reporting! Is the desktop number correctly saved to the session file `~/.lwsm/~/.lwsm/sessionData/{sessionName}`?

**Comment by Fr33maan** [comment]
I will check this. Thanks for quick answer

Le dim. 19 janv. 2020 à 23:01, Johannes Millan <notifications@github.com> a
écrit :

**Comment by Fr33maan** [comment]
Yes they was mostly on the correct screens when I look at `wmCurrentDesktopNr` `x` and `y`.
My setup is particular, I have 3 screens and 6 desktop which are only on the central screen.
It's a low priority bug I think, your lib is still very handy.
If you want to have a look at my config, it's there -> https://pastebin.com/RKfp4W6A

I'm not sure to underatnd everything about the states but it seems pretty configurable, maybe a FOCUS is messing with stuff ? Maybe the initial desktop Im on before launching the command does something wrong ?
If you want me to try out some stuff just tell me.

**Comment by Fr33maan** [comment]
I tried again and windows get opened on the correct screens. So I'm closing because I can't reproduce.
