### ISSUE TITLE
Firefox should be only run once at restore time

### ISSUE THREAD

**Issue by allentiak** [johannesjo/linux-window-session-manager#58]
## Your Environment
* Version used: 3.0.8
* Operating System and version: Debian bullseye/sid
* Desktop Environment: GNOME 3.34
* Node version: 12.6.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): 
Firefox (multiple windows)

## Expected Behavior
Even though they correspond to multiple windows, the application should be run only once (the window list is managed by Firefox itself).

## Current Behavior
Firefox is executed once per window. It displays a message error explaining that an instance of Firefox is already running per each time the program is run after the first one.

## Steps to Reproduce (for bugs)

1. Start Firefox
2. Open a X new windows in Firefox
3. Save the session
4. When restoring the session, there will be X error messages.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. As a quick work around you can manually remove the other windows from the session file (`~/.lwsm/sessionData/{your-session-name}.json`), but then their positions won't be restored. 

The best solution would probably be to provide a custom flag for that, that could be added to the session config. I am open for Pull Requests for this one, but won't probably implement it by myself any time soon, as I have a lot of other stuff on my plate...

**Comment by RodrigoATorres** [comment]
I could not reproduce this error.
Rolling back some commits, I believe [this commit](https://github.com/johannesjo/linux-window-session-manager/commit/ead936cdc8ca97123f8efa7148793b00245e9571) fixed it.

**Comment by allentiak** [comment]
Thanks for letting me know, @RodrigoATorres . I'll try the new version and let you know.

**Comment by allentiak** [comment]
@RodrigoATorres @johannesjo

It seems to work with 3.14 :-)
Thanks for your hard work!

I'll reopen this if the bug reappears.
