### ISSUE TITLE
Doesn't put applications in the third workspace.

### ISSUE THREAD

**Issue by penloy** [johannesjo/linux-window-session-manager#62]
## Your Environment

* Version used: Latest
* Operating System and version: PopOS 19.10
* Desktop Environment: Gnome
* Node version: 12.16.1
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): Unity hub, Clementine, Firefox, Monodevelop, terminal, gamehub

## Expected Behavior

* lwsm save with three different workspaces open
* lwsm restore with one workspace open
* all windows should reopen in all three workspaces respectively

## Current Behavior

* lwsm save with three diferent workspaces open
* lwsm restore with one workspace open
* workspace one and two configure themselves correctly, but all of the windows that should be in workspace three end up back in workspace one.

## Steps to Reproduce (for bugs)

1. Using gnome, have three workspaces open, with different windows in each, then type lwsm save in a terminal window
2. close all of the windows in each workspace, leaving you with no windows open
3. open a terminal and type lwsm restore

**Comment by johannesjo** [comment]
Thanks for reporting. Currently I am pretty swamped with [other stuff](https://github.com/johannesjo/super-productivity). Pull Requests would be very welcome on this.
