### ISSUE TITLE
Doesn't load Whatdesk (Whatsapp Desktop App)

### ISSUE THREAD

**Issue by f-ricchiuto** [johannesjo/linux-window-session-manager#63]
## Your Environment

* Version used: 
* Operating System and version:  elementary OS 5.1.2 Hera - 5.3.0-40-generic ~ 18.04.1-Ubuntu
* Desktop Environment: Gala
* Node version: v10.19.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore):  
- WhatDesk [Snap download page](https://snapcraft.io/whatsdesk)
## Expected Behavior
Launch the application when launching `lwsm restore`

## Current Behavior
All my apps are restored, even DockStation which is installed with Snap, but WhatDesk fails with the following error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn WhatsDesk ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
If I can give some more debugging info, please tell me how to return those informations to you!

## Steps to Reproduce (for bugs)

1. yarn globall add linux-window-session-manager
2. sudo snap install whatsdesk
3. whatsdesk
4. lwsm save
5. lwsm restore

Congrats for this project! Is the first time that I see a node app interacting with the OS this way :-)

**Comment by johannesjo** [comment]
Hey there! Please check the troubleshooting section on your issue:
https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues
