### ISSUE TITLE
Please use ~./config for storing configuration files

### ISSUE THREAD

**Issue by allentiak** [johannesjo/linux-window-session-manager#65]
## Your Environment

* Version used: 3.1.4
* OS: GNU/Linux (possibly also others UN*Xes)

## Expected Behavior

As the home directory already has enough directories, ~./config was created for config files :-)
Therefore, under GNU/Linux, lwsm settings should (ideally) be stored under ~/.config/lwsm

## Current Behavior

Under GNU/Linux, lwsm settings are stored under ~/.lwsm

**Comment by johannesjo** [comment]
Thanks for reporting! Makes sense to me! We would have to make the change backwards compatible though. Would you like to give it a shot yourself?

**Comment by allentiak** [comment]
I appreciate the offer, but don't think I have the time right now... I still have to find the time to verify 3.1.4 solves the other bug I reported :-)

**Comment by johannesjo** [comment]
Alright then! No worries.

**Comment by allentiak** [comment]
If you are looking for co-maintainers, maybe a better place to advertise it is the README?

**Comment by johannesjo** [comment]
In this particular case: I personally don't care enough about the change to be honest and have a lot of other open source stuff on my plate. It seems to annoy you, so it made sense to me, to offer you changing it yourself :)

**Comment by allentiak** [comment]
No worries :-) As I realized there were many bugs tagged as "help-wanted",
I thought my suggestion might help you getting that help from people more
likely to contribute **code** (much more valuable than bug-reporting
contributions) _to this particular project_ than me.

**Comment by ybnd** [comment]
[Here's a quick PR](https://github.com/johannesjo/linux-window-session-manager/pull/67)
