### ISSUE TITLE
lwsm: ignored legacy config directory /home/@USER/.lwsm

### ISSUE THREAD

**Issue by alexdom** [johannesjo/linux-window-session-manager#68]
Ubuntu 20.04

sessions are not saved:

`-> % lwsm save
lwsm: ignored legacy config directory /home/sasha/.lwsm
ERR: findDesktopFile() cant find file "evolution.desktop"! Searched desktopFileLocations: [
`
and so on..

**Comment by johannesjo** [comment]
Thanks for reporting. Please refer to the troubleshooting section:
https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues

If I am not mistaken there should be all information you need.

**Comment by alexdom** [comment]
Thanks for quick response! See, after installation of lwsm, there is no ~/.lwsm/config.json file. The directory is simply empty. Do I have to create one? Where can I get the pattern?

**Comment by johannesjo** [comment]
Depending on the version used the file might be located here:
`~/.config/lwsm/config.json`

**Comment by alexdom** [comment]
Here we go.. It is there. 
`> ls -1
config.json
sessionData
`
Also, wanted to mention. Is that the reason why I can't see saved sessions in the Gnome Extension in the top bar? That the sessions are not stored in the right place?
