### ISSUE TITLE
otherCmd: Generic Error 0

### ISSUE THREAD

**Issue by marden** [johannesjo/linux-window-session-manager#7]
Running in Ubuntu 16.04 gives errors:

> ~ lwsm save
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
otherCmd: Generic Error 0
Input Handler Error:  No input for desktop file path
SAVED SESSION: DEFAULT

And no session created.

**Comment by johannesjo** [comment]
Thanks for reporting. Is `~/.lwsm` writeable by node?

**Comment by marden** [comment]
`~/.lwsm` is `drwxrwxr-x`.
Chrome, Slack, Terminator, PhpStorm.

**Comment by johannesjo** [comment]
Does it work, when you only have chrome opened?

**Comment by johannesjo** [comment]
Another Question: Is Slack a chrome app? Then it should work with the latest version. See #2.

**Comment by eater** [comment]
Hi @johannesjo, I just rebooted and restored a session (the one that worked in #2), closed one Thunar window, and tried to save as a new session, and it's not saving.
```
$lwsm save cleansession
otherCmd: Generic Error 0 undefined
```

**Comment by johannesjo** [comment]
@eater: Hm weird that the error is 0 and that there is no stack provided. Could you maybe provide the contents of `.lwsm/cleansession.json` so that I could try it for myself?

**Comment by eater** [comment]
It didn't create a session file at all! Let me know what else I can do to help figure it out.

**Comment by johannesjo** [comment]
If there is no session file then this should be no different from saving a new session. Could you maybe try to narrow it down a little, e.g. by closing some of the applications before saving the session?

**Comment by eater** [comment]
Now I get the "Error 0" when I try to restore a known-good session also, even after clearing my ~/.lswm config. Attaching the known-good session file here.
[goodsession.json.txt](https://github.com/johannesjo/linux-window-session-manager/files/1202704/goodsession.json.txt)

**Comment by johannesjo** [comment]
@eater I'm having a hard time to narrow it down. Could you provide some more specs about your desktop environment and which applications you're trying to handle. Haven't run into any of these issues myself with Ubuntu 16.04 and a gnome desktop.

**Comment by eater** [comment]
I'm using Compiz's widget layer, and assigning WM_CLASS="widgy" to certain windows which I want Compiz to keep there, including a Chrome app. That may be the problem. Today I got this:
```
$lwsm restore goodsession
crx_bikioccmkafdpakkkcpdbppfkghcmihk.Google-chrome is running:  false 1 0
gvim.Gvim is running:  false 3 0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn widgy.desktop ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```
and then
```
$lwsm save goodsession2
otherCmd: Generic Error 0 undefined
Input Handler Error:  No input for desktop file path for window "Navigator.Pale moon". Please fix this manually in config file for this session in ~/.lwsm/session-name.json undefined
SAVED SESSION: goodsession2
```

**Comment by johannesjo** [comment]
That's very likely to be the issue. The tool does parse the wmClassName to identify the desktop file names, as it seemed to be the most reliable source for that. It's not ideal, but what you could do is setting either the desktopFilePath or the executableFile (this could be any command, but requires desktopFilePath not to be set) properties in your session config file manually.

**Comment by eater** [comment]
I quit every window that had a custom class name, and tried to save a new session. Still not working:
```
$ wmctrl -lx  
0x06a00018  0 nasc.Nasc             Xagain NaSC
0x00e00004 -1 xfce4-panel.Xfce4-panel  Xagain xfce4-panel
0x01600003  0 xfdesktop.Xfdesktop   Xagain Desktop
0x07000010  0 crx_bikioccmkafdpakkkcpdbppfkghcmihk.Google-chrome  Xagain Signal
0x07000029  0 crx_flejfacjooompmliegamfbpjjdlhokhj.Google-chrome  Xagain Join
0x01e0004f  0 xfce4-terminal.Xfce4-terminal  Xagain  wmctrl -lx
0x022000a7  0 Navigator.Pale moon   Xagain otherCmd: Generic Error 0 · Issue #7 · johannesjo/linux-window-session-manager - Pale Moon
0x0700004d  0 crx_kaoganeefjllmkgaaiddghcdejmncibh.Google-chrome  Xagain Logitech Media Server
0x01e03c72  0 xfce4-terminal.Xfce4-terminal  Xagain alpine
0x08000003  0 gvim.Gvim             Xagain  goodsession.json - GVIM
$ lwsm save nowidgets 
otherCmd: Generic Error 0 undefined
```
(In the wmctrl output, "Xagain" is the machine name.)

**Comment by johannesjo** [comment]
A Question: Are you using an xfce4 desktop?

**Comment by eater** [comment]
Yes sir.

**Comment by johannesjo** [comment]
Never tested the tool on such. Also: What are Navigator.Pale. nasc.Nasc, and xfdesktop.Xfdesktop?

**Comment by eater** [comment]
Navigator.Pale moon is the Pale Moon browser. [Nasc](http://parnold-x.github.io/nasc/) is a calculator application. And Xfdesktop is the desktop window.

**Comment by johannesjo** [comment]
Would be wonderful if you could narrow it down again to the apps not working. Than I can add them to the default config.

**Comment by eater** [comment]
With "Navigator.Pale moon": "palemoon.desktop" added to WM_CLASS_AND_EXECUTABLE_FILE_MAP it's working for now, even with the custom classes.

**Comment by johannesjo** [comment]
Thanks for reporting back! That's great to hear! Did you also add `xfdesktop.Xfdesktop` to the `WM_CLASS_EXCLUSIONS`?

**Comment by eater** [comment]
I added it just now -- seems to work with or without that exclusion.

**Comment by johannesjo** [comment]
Ok. That's good to know. Thanks a lot for all your effort!
