### ISSUE TITLE
Nautilus is being ignored

### ISSUE THREAD

**Issue by Algram** [johannesjo/linux-window-session-manager#8]
Hello,
first of all, thank you for the awesome piece of software, I use it daily!
I would like to know how I could include Nautilus though, currently it is being excluded int he `config.json` in `desktop_window.Nautilus` but I don't know why.

Thanks!

**Comment by johannesjo** [comment]
Thank you very much for reporting! I'm really happy to hear that someone else finds this piece of software useful! 

I'll will evaluate the problem a little further. The original reason was, that desktop_window.Nautilus was showing up in the window list even though there was no instance opened, so I assumed that it is some system level program running in the background. 

I will investigate this further and get back to you.

**Comment by johannesjo** [comment]
I'll fixed the issue by adding `"nautilus.Nautilus": "nautilus"` to `WM_CLASS_AND_EXECUTABLE_FILE_MAP` in the `~/.lwsm/config.json. I'll also add this to the default config.

**Comment by Algram** [comment]
This did not fix the issue for me unfortunately.

**Comment by johannesjo** [comment]
Could you post your `~/.lwsm/config.json` please?

**Comment by Algram** [comment]
@johannesjo Here you go
```json
{
  "GIVE_X11_TIME_TIMEOUT": 80,
  "POLL_ALL_APPS_STARTED_TIMEOUT": 2000,
  "POLL_ALL_MAX_TIMEOUT": 60000,
  "SAVE_SESSION_IN_PRETTY_FORMAT": true,
  "WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    "sun-awt-X11-XFramePeer.jetbrains-idea": "jetbrains-idea.desktop",
    "sun-awt-X11-XFramePeer.jetbrains-idea-ce": "jetbrains-idea-ce.desktop",
    "gnome-terminal-server.Gnome-terminal": "gnome-terminal",
    "VirtualBox.VirtualBox": "virtualbox.desktop",
    "Navigator.Firefox": "firefox.desktop",
    "nautilus.Nautilus": "nautilus"
  },
  "WM_CLASS_EXCLUSIONS": [
    "N/A",
    "tilda.Tilda",
    "Popup.desktop",
    "update-manager.Update-manager",
    "electron.Electron"
  ],
  "WM_META_MAP": {
    "WM_CLASS(STRING)": "wmClassName",
    "_NET_WM_STATE(ATOM)": "states",
    "_NET_WM_DESKTOP(CARDINAL)": "wmCurrentDesktopNr",
    "WM_NAME(UTF8_STRING)": "wmTitle",
    "_NET_WM_PID(CARDINAL)": "wmPid",
    "_NET_WM_WINDOW_TYPE(ATOM)": "wmType",
    "_BAMF_DESKTOP_FILE(STRING)": "executableFile"
  },
  "WM_META_MAP_NUMBER_TYPES": [
    "_NET_WM_PID(CARDINAL)",
    "_NET_WM_DESKTOP(CARDINAL)"
  ],
  "CMD": {
    "LOCATE": "locate",
    "GET_DISPLAY_ID": "xrandr --query | grep '[^s]connected '",
    "XPROP_ID": "xprop -id"
  },
  "CMD_JSFILE_PATH": "/usr/lib/node_modules/linux-window-session-manager/lib/../cmd.js",
  "JSFILE_INDEX_PATH": "/usr/lib/node_modules/linux-window-session-manager/lib/index.js"
}
```

**Comment by johannesjo** [comment]
Thanks. That looks fine. Could you maybe also execute `xprop` and then click on an open nautilus window. Maybe the WM_CLASS name differs for some reason.

**Comment by Algram** [comment]
Weird. There is no output of xprop when clicking on the Nautilus window. On different windows it works.

**Comment by johannesjo** [comment]
Ahhh OK. Probably you're running Wayland then. Unfortunately there is currently no way to manipulate Wayland application windows (which are not using XWayland). If youre running Ubuntu, you can also start your desktop in an XSession on the login screen.
