### ISSUE TITLE
Error when saving/restoring edge app shortcuts

### ISSUE THREAD

**Issue by andrewmackrodt** [johannesjo/linux-window-session-manager#83]
## Description

Saving and restoring Microsoft Edge browser "apps" fails with the error `ERR: findDesktopFile() cant find file "*_{app_id}*.desktop"! Searched desktopFileLocations:`, where `{app_id}` is the correct class, however in the case of edge apps, the leading underscore should be a hyphen, i.e. `*-{app_id}*.desktop`.

## Action version

lwsm 4.0.3

## Steps To Reproduce

<strike>Note: I experienced this with Microsoft Edge but assume it affects Google Chrome as it names its desktop files with the same convention, i.e. `{browser}-{app_id}-{profile}.desktop`. I am providing instructions to create an "app" for Chrome as I assume most users will not have Edge installed.

1. Open a site in Google Chrome
2. From the settings icon, select `Settings > More tools > Create shortcut...`
3. Ensure `Open as window` is selected
4. Click `Create`</strike>
5. Close open browser windows including the app window (probably not required)
6. Open the "app" shortcut from Applications or the equivalent depending on your desktop environment
7. Run `lwsm save` from a terminal
8. The error described in the description is generated causing `lwsm` to fail with an `UnhandledPromiseRejectionWarning`

## Expected behavior

The `.desktop` files should be found and saving/restoring should work.

**Comment by johannesjo** [comment]
This does work already for chrome and also brave. I gladly accept PRs to make this work with microsoft edge as well.

**Comment by andrewmackrodt** [comment]
Ah, indeed Chrome does work! I'll try to have a look this weekend how Chrome is handled and can hopefully apply the same principles to Microsoft Edge and open a PR. Thanks for the great project btw :).
