### ISSUE TITLE
Not working for evince

### ISSUE THREAD

**Issue by patrickwoolf** [johannesjo/linux-window-session-manager#87]
Evince doesn't reopen. Other windows do.

**Comment by johannesjo** [comment]
Thanks for reporting. Did you try the troubleshooting seciton:
https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues

**Comment by patrickwoolf** [comment]
I tried executing `xprop` on Evince, but the mouse could not be pressed over Evince.
After some search, the WM_CLASS of Evince is `"evince", "Evince"`. So I added `"evince.Evince": "org.gnome.Evince.desktop"` to the config.json. But the lwsm save still doesn't detect Evince.

![image](https://user-images.githubusercontent.com/43380000/118807847-61050680-b8db-11eb-91f8-175ca99cea3d.png)

**Comment by johannesjo** [comment]
Are you running on wayland by any chance?

**Comment by patrickwoolf** [comment]
Yes, sorry I missed that🗿 Thanks a lot for your support.

**Comment by johannesjo** [comment]
Alright, no problem! :)

**Comment by curiousercreative** [comment]
should this be closed @johannesjo

**Comment by johannesjo** [comment]
@curiousercreative yes, thank you!
