### ISSUE TITLE
Pass parameters to application

### ISSUE THREAD

**Issue by Xenorage** [johannesjo/linux-window-session-manager#90]
Problem Statement

 {
          "windowId": "0x2e00006",
          "windowIdDec": 48234502,
          "wmCurrentDesktopNr": 0,
          "states": [],
          "wmType": "_KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 19320,
          "wmClassName": "peony.peony-qt",
          "x": 3840,
          "y": 27,
          "width": 2560,
          "height": 1440,
          "simpleName": "peony-qt",
          "executableFile": "peony1",
          "desktopFilePath": "/usr/share/applications/peony.desktop"
        },
Iam trying to open the desktop folder in file manager. 
it only opens my home folder.
Is there any was to pass a parameter to the app?
"peony Desktop" command would open the Desktop folder.
"executableFile": "peony Desktop" 
still opens home dir.
"executableFile": "peony1" 
Still opens home dir, so this data is just ignored.
"desktopFilePath": "/usr/share/applications/peony.desktop Desktop"
Does not open the peony app.
## :grey_question: Possible Solution

Maybe an "executableFileParameters": "Desktop" option that would pass the the parameter to the file when starting it.

Edit : OK, never mind. The solution was.
 {
          "windowId": "0x2e00006",
          "windowIdDec": 48234502,
          "wmCurrentDesktopNr": 0,
          "states": [],
          "wmType": "_KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 19320,
          "wmClassName": "peony.peony-qt",
          "x": 3840,
          "y": 27,
          "width": 2560,
          "height": 1440,
          "simpleName": "peony-qt",
          "executableFile": "peony Desktop"
        }
Have to delete the desktopFilePath line, then executableFile will be executed and you can pass parameter with that.

**Comment by johannesjo** [comment]
Glad that it works now for you.
